# Docker para produccion o stage
FROM gradle:8.9.0-jdk21

ENV RABBIT_URL=host.docker.internal
ENV MONGO_URL=mongodb://host.docker.internal
ENV AUTH_SERVICE_URL=http://host.docker.internal:3000

WORKDIR /app

RUN curl -L https://github.com/nmarsollier/ecommerce_catalog_java/tarball/master | tar xz --strip=1
RUN gradle build fatJar

# Puerto de Catalog Service
EXPOSE 3002

CMD java -jar ./build/libs/catalog_java-all.jar
